# conda env create --file environment.yml
# mamba env create --file environment.yml
name: expected_credit_loss
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - jupyter
  - jupyterlab
  - matplotlib
  - numpy
  - pandas
  - pip
  - plotly
  - python=3.12
  - seaborn
  - scikit-learn
  - statsmodels 
  - xgboost
  - shap
  - polars
  - pyarrow